import { LegalLayout, LegalSection } from '@/components/site/legal-layout'

export const metadata = {
  title: 'Terms',
  description: 'The terms of use for the HiArt free beta.',
}

export default function TermsPage() {
  return (
    <LegalLayout
      eyebrow="Terms"
      title="The deal, in plain terms."
      updated="4 August 2026"
      intro="HiArt is offered as a free beta. These terms describe what you can expect from us, and what we expect from you."
    >
      <LegalSection title="The service">
        <p>
          HiArt produces an AI-assisted assessment of how a visual may be perceived. It is an
          opinion generated by a model, not a measurement, a guarantee, or professional design
          advice. You remain responsible for what you publish.
        </p>
      </LegalSection>

      <LegalSection title="Beta status">
        <p>
          The service is free during the beta and limited to three analyses per account per UTC day
          and three Brand Profiles. Features may change, and we may pause or end the beta. We do not
          promise uninterrupted availability.
        </p>
      </LegalSection>

      <LegalSection title="What you upload">
        <p>
          You must have the right to upload each image you submit. Do not upload material that
          infringes someone else&apos;s rights, that is unlawful, or that depicts a person in a way
          they have not agreed to.
        </p>
        <p>
          Do not use HiArt to evaluate or rank people, to build profiles of individuals, or to
          produce material intended to deceive. The model is instructed to refuse that work, and
          accounts used that way may be suspended.
        </p>
        <p>You keep ownership of everything you upload. We do not claim rights over your work.</p>
      </LegalSection>

      <LegalSection title="Your account">
        <p>
          You are responsible for activity on your account. Do not attempt to circumvent the daily
          limits, access other users&apos; data, or interfere with the service.
        </p>
      </LegalSection>

      <LegalSection title="Liability">
        <p>
          The service is provided as-is during the beta. To the extent permitted by law, we are not
          liable for losses arising from decisions you make based on a HiArt report.
        </p>
      </LegalSection>

      <LegalSection title="Changes">
        <p>
          We may update these terms as the product develops. Material changes will be reflected in
          the date at the top of this page.
        </p>
      </LegalSection>
    </LegalLayout>
  )
}
